version: '3'
services:
  python3:
    restart: always
    build: ./ubpy
    container_name: 'python3'
    working_dir: /root/
    tty: true
    volumes:
      - ./share:/etc/share

  ubuntunmap:
#    restart: always
    build: ./ubuntunmap
    container_name: 'ubuntunmap'
#    tty: true
    volumes:
      - ./share:/etc/share


  ubuntuman:
    restart: always
    build: ./ubuntuman
    container_name: 'ubuntuman'
    tty: true
    volumes:
      - ./share:/etc/share


